id: I12EE5BC5
legacy_id: P003125
ocr_import_info:
  bdrc_scan_id: W00EGS1016798
  source: bdrc
  ocr_info:
    timestamp: '2020-03-28T04:09:20'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-29T10:17:54.432947+00:00'
last_modified: 2022-08-29 18:18:12.708056
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W00EGS1016798
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW00EGS1016798
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གདན་ས་ཆེན་པོ་དཔལ་དྭགས་ལྷ་སྒམ་པོའི་ངོ་མཚར་གྱི་བོད་པ་དད་པའི་གཏེར་ཆེན།
  author: སྒམ་པོ་སྐུ་སྐྱེ་ནོར་བུ་རྒྱན་པ།
statistics:
  ocr_word_mean_confidence_index: 0.5606791695254266
  ocr_word_median_confidence_index: 0.550000011920929
quality: null
bases:
  I01CT1759:
    source_metadata:
      id: http://purl.bdrc.io/resource/I01CT1759
      total_pages: 58
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I01CT1759.txt
    statistics:
      ocr_word_median_confidence_index: 0.550000011920929
      ocr_word_mean_confidence_index: 0.5606791695254266
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
